trigger-dependency-injection/main/default/objects/HandlerMethod__mdt/HandlerMethod__mdt.object-meta.xml
<CustomObject>
    <description>Apex methods called by triggers (handlers, service managers...). Record a method as this custom metadata is necessary to relate a handler to the proper calling trigger.</description>
    <label>Handler Method</label>
    <pluralLabel>Handler Methods</pluralLabel>
</CustomObject>

force-app/main/default/objects/HandlerMethod__mdt/fields/CallingTrigger__c.field-meta.xml
<CustomField>
    <fullName>CallingTrigger__c</fullName>
    <label>Calling Trigger</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HandlerMethod__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HandlerMethod__mdt/fields/IndexOfExecution__c.field-meta.xml
<CustomField>
    <fullName>IndexOfExecution__c</fullName>
    <inlineHelpText>Enter a number defining the order of execution of the method. A method with the index 1 will execute before a method with the index 2.</inlineHelpText>
    <label>Index of Execution</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HandlerMethod__mdt/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>Method Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

trigger-dependency-injection/main/default/objects/HandlerMethod__mdt/fields/Moments__c.field-meta.xml
<CustomField>
    <fullName>Moments__c</fullName>
    <inlineHelpText>Enter the moment the method shall execute (comma-separated): before, after.</inlineHelpText>
    <label>Moments</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HandlerMethod__mdt/fields/Operations__c.field-meta.xml
<CustomField>
    <fullName>Operations__c</fullName>
    <inlineHelpText>Enter the operations which shall execute the method (comma-separated): insert, update, delete, undelete</inlineHelpText>
    <label>Operations</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Caller.cls
public with sharing class Caller {
    
    public static void callHandlers(String callingTrigger) {
        
        List<HandlerMethod__mdt> methods = [SELECT DeveloperName, ClassName__c, MethodName__c, Moments__c, Operations__c
                                            FROM HandlerMethod__mdt
                                            WHERE Active__c = true AND CallingTrigger__c = :callingTrigger
                                            ORDER BY IndexOfExecution__c ASC];
        
        Map<String, Callable> instanciatedClasses = new Map<String, Callable> ();
        String currentClassName;
        for (HandlerMethod__mdt method : methods) {
            
            Callable callableClass;
            if (currentClassName == null || instanciatedClasses.get(method.ClassName__c) == null) {
                callableClass = (Callable)Type.forName(method.ClassName__c).newInstance();
                instanciatedClasses.put(method.ClassName__c, callableClass);
            } else {
                callableClass = instanciatedClasses.get(method.ClassName__c);
            }
            currentClassName = method.ClassName__c;
            
            List<String> operations = method.Operations__c.toLowerCase().deleteWhitespace().split(',');
            Map<String, Object> parameters = new Map<String, Object> {
                'records' => Trigger.new,
                'oldRecords' => Trigger.oldMap
            };
            
            if (Trigger.isBefore && method.Moments__c.toLowerCase().deleteWhitespace().contains('before')) {
                if (Trigger.isInsert && operations.contains('insert')) {
                    System.debug(callableClass.call(method.MethodName__c, parameters));
                }
                if (Trigger.isUpdate && operations.contains('update')) {
                    System.debug(callableClass.call(method.MethodName__c, parameters));
                }
                if (Trigger.isDelete && operations.contains('delete')) {
                    System.debug(callableClass.call(method.MethodName__c, parameters));
                }
            }
            
            if (Trigger.isAfter && method.Moments__c.toLowerCase().deleteWhitespace().contains('after')) {
                if (Trigger.isInsert && operations.contains('insert')) {
                    System.debug(callableClass.call(method.MethodName__c, parameters));
                }
                if (Trigger.isUpdate && operations.contains('update')) {
                    System.debug(callableClass.call(method.MethodName__c, parameters));
                }
                if (Trigger.isDelete && operations.contains('delete')) {
                    System.debug(callableClass.call(method.MethodName__c, parameters));
                }
                if (Trigger.isUndelete && operations.contains('undelete')) {
                    System.debug(callableClass.call(method.MethodName__c, parameters));
                }
            }
            
        }
        
    }
    
}