trigger-dependency-injection/main/default/objects/HandlerMethod__mdt/HandlerMethod__mdt.object-meta.xml
<CustomObject>
    <description>Apex methods called by triggers (handlers, service managers...). Record a method as this custom metadata is necessary to relate a handler to the proper calling trigger.</description>
    <label>Handler Method</label>
    <pluralLabel>Handler Methods</pluralLabel>
</CustomObject>

force-app/main/default/objects/HandlerMethod__mdt/fields/CallingTrigger__c.field-meta.xml
<CustomField>
    <fullName>CallingTrigger__c</fullName>
    <label>Calling Trigger</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HandlerMethod__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HandlerMethod__mdt/fields/IndexOfExecution__c.field-meta.xml
<CustomField>
    <fullName>IndexOfExecution__c</fullName>
    <inlineHelpText>Enter a number defining the order of execution of the method. A method with the index 1 will execute before a method with the index 2.</inlineHelpText>
    <label>Index of Execution</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HandlerMethod__mdt/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>Method Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

trigger-dependency-injection/main/default/objects/HandlerMethod__mdt/fields/Moment__c.field-meta.xml
<CustomField>
    <fullName>Moment__c</fullName>
    <label>Moment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>before</fullName>
                <default>true</default>
                <label>before</label>
            </value>
            <value>
                <fullName>after</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

trigger-dependency-injection/main/default/objects/HandlerMethod__mdt/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>insert</fullName>
                <default>true</default>
                <label>insert</label>
            </value>
            <value>
                <fullName>update</fullName>
            </value>
            <value>
                <fullName>delete</fullName>
            </value>
            <value>
                <fullName>undelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

trigger-dependency-injection/main/default/objects/HandlerMethod__mdt/fields/Parameter1__c.field-meta.xml
<CustomField>
    <fullName>Parameter1__c</fullName>
    <label>Parameter 1</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>null</fullName>
            </value>
            <value>
                <fullName>Trigger.new</fullName>
            </value>
            <value>
                <fullName>Trigger.newMap</fullName>
            </value>
            <value>
                <fullName>Trigger.old</fullName>
            </value>
            <value>
                <fullName>Trigger.oldMap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

trigger-dependency-injection/main/default/objects/HandlerMethod__mdt/fields/Parameter2__c.field-meta.xml
<CustomField>
    <fullName>Parameter2__c</fullName>
    <label>Parameter 2</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>null</fullName>
            </value>
            <value>
                <fullName>Trigger.new</fullName>
            </value>
            <value>
                <fullName>Trigger.newMap</fullName>
            </value>
            <value>
                <fullName>Trigger.old</fullName>
            </value>
            <value>
                <fullName>Trigger.oldMap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

trigger-dependency-injection/main/default/classes/Caller.cls
/**
* @author Rémi Le Guin
* @date 09/04/2019
* @description Trigger handlers caller breaking up the dependencies between triggers and classes called by the triggers (handlers, service managers...). The handler classes shall implement the System.Callable interface provided by Salesforce.
*/
global without sharing class Caller {

    /**
    * @description Get the custom metadata containing information on the handlers and execute them.
    * @param callingTrigger Name of the trigger calling the method.
    */
    global static void callHandlers(String callingTrigger) {
        List<HandlerMethod__mdt> methods = [SELECT ClassName__c, MethodName__c, Moment__c, Operation__c, Parameter1__c, Parameter2__c
                                            FROM HandlerMethod__mdt
                                            WHERE Active__c = true AND CallingTrigger__c = :callingTrigger
                                            ORDER BY IndexOfExecution__c ASC];
        // Stores the handler classes which already may have been instanciated.
        Map<String, Callable> instanciatedClasses = new Map<String, Callable> ();
        for (HandlerMethod__mdt method : methods) {
            Callable callableClass = instanciateHandler(method, instanciatedClasses);
            Map<String, Object> parameters = setParameters(method);
            callHandler(method, callableClass, parameters);
        }
    }

    private static Map<String, Object> setParameters(HandlerMethod__mdt method) {
        Map<String, Object> parameters = new Map<String, Object> ();
        switch on method.Parameter1__c {
            when 'null' {
                parameters.put('parameter1', null);
            }
            when 'Trigger.new' {
                parameters.put('parameter1', Trigger.new);
            }
            when 'Trigger.newMap' {
                parameters.put('parameter1', Trigger.newMap);
            }
            when 'Trigger.old' {
                parameters.put('parameter1', Trigger.old);
            }
            when 'Trigger.oldMap' {
                parameters.put('parameter1', Trigger.oldMap);
            }
            when else {
                System.debug('No first parameter.');
            }
        }
        switch on method.Parameter2__c {
            when 'null' {
                parameters.put('parameter2', null);
            }
            when 'Trigger.new' {
                parameters.put('parameter2', Trigger.new);
            }
            when 'Trigger.newMap' {
                parameters.put('parameter2', Trigger.newMap);
            }
            when 'Trigger.old' {
                parameters.put('parameter2', Trigger.old);
            }
            when 'Trigger.oldMap' {
                parameters.put('parameter2', Trigger.oldMap);
            }
            when else {
                System.debug('No second parameter.');
            }
        }
        return parameters;
    }

    /**
    * @description Instanciates and stores a handler class or get it from the Map if it has previously been.
    * @param method Custom metadata containing information about the method to execute.
    * @return Instanciated class implementing Callable interface.
    */
    private static Callable instanciateHandler(HandlerMethod__mdt method, Map<String, Callable> instanciatedClasses) {
        if (instanciatedClasses.isEmpty() || instanciatedClasses.get(method.ClassName__c) == null) {
            Callable callableClass = (Callable)Type.forName(method.ClassName__c).newInstance();
            // Stores the instanciated handler class in case it is called again later.
            instanciatedClasses.put(method.ClassName__c, callableClass);
            return callableClass;
        }
        else {
            // If the class has already been instanciated, get it from the Map where it has previously been stored.
            return instanciatedClasses.get(method.ClassName__c);
        }
    }

    /**
    * @description Calls the handler method to be executed according the Trigger context.
    * @param method Custom metadata containing information about the method to execute.
    * @param callableClass Class implementing the Callable interface that has been instanciated beforehand.
    * @param parameters Inputs to pass to the method.
    */
    private static void callHandler(HandlerMethod__mdt method, Callable callableClass, Map<String, Object> parameters) {
        // The System.debug operations use the call method from the Callable interface implemented in the handler class.
        // The call method dynamically calls the informed method in the handler and returns back a state message.
        if (Trigger.isBefore && method.Moment__c == 'before') {
            if (Trigger.isInsert && method.Operation__c == 'insert') {
                System.debug(callableClass.call(method.MethodName__c, parameters));
            }
            if (Trigger.isUpdate && method.Operation__c == 'update') {
                System.debug(callableClass.call(method.MethodName__c, parameters));
            }
            if (Trigger.isDelete && method.Operation__c == 'delete') {
                System.debug(callableClass.call(method.MethodName__c, parameters));
            }
        }
        if (Trigger.isAfter && method.Moment__c == 'after') {
            if (Trigger.isInsert && method.Operation__c == 'insert') {
                System.debug(callableClass.call(method.MethodName__c, parameters));
            }
            if (Trigger.isUpdate && method.Operation__c == 'update') {
                System.debug(callableClass.call(method.MethodName__c, parameters));
            }
            if (Trigger.isDelete && method.Operation__c == 'delete') {
                System.debug(callableClass.call(method.MethodName__c, parameters));
            }
            if (Trigger.isUndelete && method.Operation__c == 'undelete') {
                System.debug(callableClass.call(method.MethodName__c, parameters));
            }
        }
    }
    
}